% Import data
dataset = readtable('train.csv');
% Working variable
data = dataset;

%%

% Removal of 'pool-related' non-informative rows
data(data.PoolArea > 0, :) = [];

%%

% Garage ...
hasGarage = zeros(height(data),1);
hasGarage(data.GarageArea > 0) = 1;

data = addvars( ...
    data, ...
    hasGarage, ...
    'Before', ...
    'GarageArea', ...
    'NewVariableNames', ...
    'hasGarage' ...
);

clear hasGarage

%%

% After data exploration low informative-content variables are removed
data = removevars( ...
    data, ...
    { ...
        'Id', 'Street', 'Alley', 'Utilities', 'Condition1', ...
        'Condition2', 'HouseStyle', 'Exterior1st', 'Exterior2nd', ...
        'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', ...
        'BsmtUnfSF', 'Electrical', 'LowQualFinSF', 'TotRmsAbvGrd', ...
        'Functional', 'FireplaceQu', 'GarageType', 'GarageYrBlt', ...
        'GarageFinish', 'GarageQual', 'WoodDeckSF', 'OpenPorchSF', ...
        'EnclosedPorch', 'x3SsnPorch', 'ScreenPorch', 'PoolArea', ...
        'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', ...
        'YrSold', 'SaleType', ...
    } ...
);

%%

% Missing values analysis
nanCount = sum(ismissing(data))
nanIndices = find(nanCount > 0)

%%

% Missing values management
for i = nanIndices
    data.(i) = fillmissing( ...
        data.(i), ...
        'constant', ...
        mean(i(~isnan(i))) ...
    );
end

clear nanCount
clear nanIndices
clear i

%%